package com.example.releaf.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import com.example.releaf.ui.viewmodel.AppLanguage
import com.example.releaf.ui.viewmodel.ThemeViewModel

object AppStrings {
    val en = mapOf(
        // App chrome / nav
        "app_name" to "Releaf",
        "search_placeholder" to "Search...",
        "activity" to "Activity",
        "garden" to "Garden",
        "profile" to "Profile",
        "map" to "Map",
        "settings" to "Settings",
        "theme" to "Theme",
        "language" to "Additional Language",
        "logout" to "Log out",
        "favourite_toilets" to "Favourite Toilets",
        "nearest_toilet" to "Nearest Toilet",
        "nearest_trash_can" to "Nearest Trash Can",
        "my_location" to "My location",
        "select_language" to "Select Language",
        "points" to "Points",
        "gems" to "Gems",
        "harvest" to "Harvest",
        "growing" to "Growing...",
        "empty_pot" to "Empty Pot",
        "planted" to "Planted",
        "garden_plot" to "My Garden Plot",
        "rewards" to "Rewards",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "reward" to "Reward",
        "back" to "Back",
        "retry" to "Retry",
        "refresh" to "Refresh",
        "cancel" to "Cancel",
        "close" to "Close",
        "save" to "Save",
        "claim" to "Claim",

        // Auth
        "login_subtitle" to "Log in to keep your garden growing",
        "email_label" to "Email",
        "password_label" to "Password",
        "name_label" to "Name",
        "confirm_password_label" to "Confirm password",
        "forgot_password" to "Forgot password?",
        "login_btn" to "Log In",
        "register_btn" to "Register",
        "create_account" to "Create account",
        "join_releaf" to "Join Releaf and start growing",
        "already_have_account" to "Already have an account?",
        "dont_have_account" to "Don't have an account?",
        "pw_too_short" to "Password must be at least 6 characters",
        "pw_mismatch" to "Passwords do not match",
        "invalid_email_fmt" to "Invalid email address — e.g. name@example.com",
        "name_required" to "Please enter your name",
        "verify_title" to "Verify your email",
        "verify_sent_prefix" to "We sent a verification link to ",
        "verify_step1" to "1. Open your email and tap the confirmation link",
        "verify_step2" to "2. Return to the app and tap Continue below",
        "verified_continue" to "I've verified — Continue",
        "resend_email_btn" to "Resend verification email",
        "forgot_title" to "Forgot Password",
        "forgot_intro" to "Enter your email and we'll send you a link to reset your password.",
        "send_reset_btn" to "Send Reset Link",
        "check_email_title" to "Check your email",
        "reset_sent_prefix" to "We sent a password reset link to ",
        "reset_sent_suffix" to ". Click the link to set a new password, then come back and log in.",
        "back_to_login" to "Back to Login",
        "setpw_title" to "Set New Password",
        "setpw_intro" to "Email verified! Choose a new password for your account.",
        "new_password_label" to "New password",
        "confirm_new_password_label" to "Confirm new password",
        "save_password_btn" to "Save Password",

        // Garden
        "plot_tap_hint" to "Tap any plant below to water or fertilize it.",
        "water" to "Water",
        "fertilize" to "Fertilize",
        "uses_left_today" to "Uses left today: ",
        "water_dialog" to "💧 Water +50 EXP",
        "fertilize_dialog" to "🌱 Fertilize +50 EXP",
        "active_plant" to "Slot %1\$d: Active Plant",
        "slot_empty" to "Slot %1\$d: Empty Pot",

        // Activity
        "loading_quests" to "Loading daily quests...",
        "no_quests" to "No quests available right now.",
        "quest_reward_claim" to "CLAIM REWARD",
        "quest_completed" to "COMPLETED",
        "refreshed_ok" to "Refreshed ✓",
        "exp_label" to "EXP",

        // Rewards
        "garden_seeds_title" to "Garden Seeds",
        "claimable_titles_title" to "Claimable Titles",
        "avatar_frames_title" to "Avatar Frames",
        "buy" to "Buy",
        "owned_ok" to "Owned ✓",
        "frames_owned_hint" to "Owned - pick it in Profile → frame picker",
        "equip" to "Equip",
        "equipped_ok" to "Equipped ✓",
        "currently_equipped" to "Currently equipped",
        "unlocked_tap_equip" to "Unlocked - tap to equip",
        "requires_exp_fmt" to "Requires %1\$d EXP",
        "frames_buy_hint" to "Frames are bought with 💎 Gems + 🪙 spendable Points (earn 🪙 by watering & quests, 💎 by watering and Pro daily rewards).",
        "seed_planted" to "🌱 Planted in Garden Plot",
        "seed_unlocked_fmt" to "Unlocked (%1\$d/%2\$d EXP)",
        "seed_requires_fmt" to "Requires %1\$d EXP (%2\$d/%1\$d)",

        // Profile
        "my_garden_plants" to "My Garden & Plants",
        "their_garden_fmt" to "%1\$s's Garden",
        "garden_plants_collection" to "Garden Plants Collection",
        "achievements_fmt" to "Achievements (%1\$d/%2\$d)",
        "quick_options" to "Quick Options",
        "favourite_locations" to "Favourite Locations",
        "settings_prefs" to "Settings & App Preferences",
        "settings_account" to "Account",
        "settings_about" to "About Us",
        "settings_notify" to "Notification Settings",
        "settings_clear_cache" to "Clear Cache",
        "settings_updates" to "Updates",
        "view_garden" to "View Garden",
        "slot_label_fmt" to "Slot %1\$d: %2\$s",

        // Map / POI / notifications
        "notifications" to "Notifications",
        "mark_all_read" to "Mark all read",
        "no_notifications" to "No notifications yet",
        "add_new_toilet" to "Add New Toilet",
        "add_new_trash" to "Add New Trash Can",
        "toilet" to "Toilet",
        "trash_can" to "Trash Can",
        "location_label" to "Location (e.g. Level 1)",
        "name_required_ast" to "Name *",
        "paid" to "Paid",
        "free" to "Free",
        "add_photo" to "Add Photo",
        "change_photo" to "Change Photo",
        "add" to "Add",
        "all" to "All",
        "unverified" to "Unverified",
        "clean" to "Clean",
        "average" to "Average",
        "dirty" to "Dirty",
        "filter_paid" to "Paid",
        "filter_free" to "Free",
        "direction" to "Direction",
        "comment" to "Comment",
        "verify" to "Verify",
        "not_exist" to "Not Exist",
        "updating" to "Updating...",
        "verified" to "Verified",
        "photo_uploaded" to "Photo uploaded!",
        "photo_failed" to "Photo upload failed",
        "no_map_app" to "No map application is available on this device.",
        "location_off_title" to "Location is off",
        "location_off_text" to "Turn on GPS / location services to use this feature.",
        "open_location_settings" to "Open Location Settings",
        "no_internet_title" to "No internet connection",
        "no_internet_text" to "Releaf needs Wi-Fi or mobile data. Please turn on Wi-Fi or mobile data and try again.",
        "open_settings" to "Open Settings",
        "ok" to "OK",
        "choose_gallery" to "Choose from Gallery",
        "gallery_hint" to "Select an existing photo from device",
        "take_camera" to "Take Photo with Camera",
        "camera_hint" to "Capture a new photo right now",
        "attach_photo_title" to "Attach Photo",
        "upload_facility_photo" to "Upload Facility Photo",
        "photo_attached" to "Photo attached to comment ✓",
        "get_pro" to "Get Pro",
        "pro" to "Pro",
        "subscribe_btn" to "Subscribe Now • $2.99 / mo",
        "vip_only" to "VIP only",
        "edit_banner" to "Edit Banner",

        // POI status / result messages (shown inline)
        "too_far_fmt" to "You must be at the location to do this (you are %s m away).",
        "already_verified" to "You already verified this POI.",
        "now_verified" to "POI is now verified!",
        "verification_counted" to "Verification recorded.",
        "verify_failed" to "Could not record your verification. Check your connection and try again.",
        "already_reported" to "You already reported this POI.",
        "now_unverified" to "Too many reports. POI is now unverified.",
        "removed_poi" to "POI has been removed due to reports.",
        "report_counted" to "Report recorded.",
        "report_failed" to "Could not record your report. Check your connection and try again.",

        // Comments
        "comments_title" to "Comments",
        "add_comment_hint" to "Add a comment...",
        "no_comments" to "No comments yet",
        "word_limit_exceeded" to "Word limit exceeded! (Max 500 words)",
        "word_count_fmt" to "%1\$d / 500 words",
        "edit_comment" to "Edit Comment",
        "delete" to "Delete",
        "report" to "Report",
        "edit" to "Edit",
        "view_full_profile" to "View Full Profile",
        "remove_from_favs" to "Remove from favourites",

        // Map strings
        "found_nearest" to "Found nearest",
        "none_found" to "No toilets or trash cans found.",
        "poi_created" to "POI created!",
        "create_failed" to "Failed to create POI",
        "too_close" to "A POI already exists within 5m of this location."
    )

    val zh = mapOf(
        // App chrome / nav
        "app_name" to "Releaf",
        "search_placeholder" to "搜索...",
        "activity" to "活动",
        "garden" to "花园",
        "profile" to "个人资料",
        "map" to "地图",
        "settings" to "设置",
        "theme" to "主题",
        "language" to "附加语言",
        "logout" to "退出登录",
        "favourite_toilets" to "收藏的厕所",
        "nearest_toilet" to "最近的厕所",
        "nearest_trash_can" to "最近的垃圾桶",
        "my_location" to "我的位置",
        "select_language" to "选择语言",
        "points" to "积分",
        "gems" to "宝石",
        "harvest" to "收获",
        "growing" to "生长中...",
        "empty_pot" to "空盆",
        "planted" to "已种植",
        "garden_plot" to "我的花园",
        "rewards" to "奖励",
        "unlocked" to "已解锁",
        "locked" to "未解锁",
        "reward" to "奖励",
        "back" to "返回",
        "retry" to "重试",
        "refresh" to "刷新",
        "cancel" to "取消",
        "close" to "关闭",
        "save" to "保存",
        "claim" to "领取",

        // Auth
        "login_subtitle" to "登录以继续照料你的花园",
        "email_label" to "邮箱",
        "password_label" to "密码",
        "name_label" to "姓名",
        "confirm_password_label" to "确认密码",
        "forgot_password" to "忘记密码？",
        "login_btn" to "登录",
        "register_btn" to "注册",
        "create_account" to "创建账户",
        "join_releaf" to "加入Releaf，开始种植",
        "already_have_account" to "已有账户？",
        "dont_have_account" to "还没有账户？",
        "pw_too_short" to "密码至少需要6个字符",
        "pw_mismatch" to "两次输入的密码不一致",
        "invalid_email_fmt" to "邮箱格式无效——例如 name@example.com",
        "name_required" to "请输入你的姓名",
        "verify_title" to "验证你的邮箱",
        "verify_sent_prefix" to "我们已向以下邮箱发送验证链接：",
        "verify_step1" to "1. 打开邮箱并点击确认链接",
        "verify_step2" to "2. 返回应用并点击下方“继续”",
        "verified_continue" to "我已验证——继续",
        "resend_email_btn" to "重新发送验证邮件",
        "forgot_title" to "忘记密码",
        "forgot_intro" to "输入你的邮箱，我们会发送一封重置密码的链接。",
        "send_reset_btn" to "发送重置链接",
        "check_email_title" to "查看你的邮箱",
        "reset_sent_prefix" to "我们已向 ",
        "reset_sent_suffix" to " 发送重置链接。点击链接设置新密码，然后返回登录。",
        "back_to_login" to "返回登录",
        "setpw_title" to "设置新密码",
        "setpw_intro" to "邮箱已验证！为你的账户设置新密码。",
        "new_password_label" to "新密码",
        "confirm_new_password_label" to "确认新密码",
        "save_password_btn" to "保存密码",

        // Garden
        "plot_tap_hint" to "点击下方任意植物即可浇水或施肥。",
        "water" to "浇水",
        "fertilize" to "施肥",
        "uses_left_today" to "今日剩余：",
        "water_dialog" to "💧 浇水 +50 EXP",
        "fertilize_dialog" to "🌱 施肥 +50 EXP",
        "active_plant" to "槽位%1\$d：种植中",
        "slot_empty" to "槽位%1\$d：空盆",

        // Activity
        "loading_quests" to "正在加载每日任务...",
        "no_quests" to "当前没有可用任务。",
        "quest_reward_claim" to "领取奖励",
        "quest_completed" to "已完成",
        "refreshed_ok" to "已刷新 ✓",
        "exp_label" to "经验",

        // Rewards
        "garden_seeds_title" to "花园种子",
        "claimable_titles_title" to "可领取称号",
        "avatar_frames_title" to "头像边框",
        "buy" to "购买",
        "owned_ok" to "已拥有 ✓",
        "frames_owned_hint" to "已拥有——在“个人资料→边框”中选择佩戴",
        "equip" to "装备",
        "equipped_ok" to "已装备 ✓",
        "currently_equipped" to "当前已装备",
        "unlocked_tap_equip" to "已解锁——点击装备",
        "requires_exp_fmt" to "需要 %1\$d EXP",
        "frames_buy_hint" to "边框使用💎宝石+🪙可花费积分购买（浇水、任务获得🪙，浇水和Pro每日奖励获得💎）。",
        "seed_planted" to "🌱 已种植到花园",
        "seed_unlocked_fmt" to "已解锁（%1\$d/%2\$d EXP）",
        "seed_requires_fmt" to "需要 %1\$d EXP（%2\$d/%1\$d）",

        // Profile
        "my_garden_plants" to "我的花园与植物",
        "their_garden_fmt" to "%1\$s的花园",
        "garden_plants_collection" to "花园植物收藏",
        "achievements_fmt" to "成就（%1\$d/%2\$d）",
        "quick_options" to "快捷选项",
        "favourite_locations" to "收藏地点",
        "settings_prefs" to "设置与应用偏好",
        "settings_account" to "账户",
        "settings_about" to "关于我们",
        "settings_notify" to "通知设置",
        "settings_clear_cache" to "清除缓存",
        "settings_updates" to "更新",
        "view_garden" to "查看花园",
        "slot_label_fmt" to "槽位%1\$d：%2\$s",

        // Map / POI / notifications
        "notifications" to "通知",
        "mark_all_read" to "全部已读",
        "no_notifications" to "暂无通知",
        "add_new_toilet" to "添加新厕所",
        "add_new_trash" to "添加新垃圾桶",
        "toilet" to "厕所",
        "trash_can" to "垃圾桶",
        "location_label" to "位置（例如 1楼）",
        "name_required_ast" to "名称 *",
        "paid" to "收费",
        "free" to "免费",
        "add_photo" to "添加照片",
        "change_photo" to "更换照片",
        "add" to "添加",
        "all" to "全部",
        "unverified" to "未验证",
        "clean" to "干净",
        "average" to "一般",
        "dirty" to "脏乱",
        "filter_paid" to "收费",
        "filter_free" to "免费",
        "direction" to "路线",
        "comment" to "评论",
        "verify" to "验证",
        "not_exist" to "不存在",
        "updating" to "更新中...",
        "verified" to "已验证",
        "photo_uploaded" to "照片上传成功！",
        "photo_failed" to "照片上传失败",
        "no_map_app" to "此设备上没有可用的地图应用。",
        "location_off_title" to "定位已关闭",
        "location_off_text" to "请开启GPS/定位服务后再使用此功能。",
        "open_location_settings" to "打开定位设置",
        "no_internet_title" to "没有网络连接",
        "no_internet_text" to "Releaf需要使用Wi-Fi或移动数据。请开启Wi-Fi或移动数据后重试。",
        "open_settings" to "打开设置",
        "ok" to "确定",
        "choose_gallery" to "从相册选择",
        "gallery_hint" to "从设备中选择现有照片",
        "take_camera" to "用相机拍摄",
        "camera_hint" to "立即拍摄一张新照片",
        "attach_photo_title" to "添加照片",
        "upload_facility_photo" to "上传设施照片",
        "photo_attached" to "照片已添加到评论 ✓",
        "get_pro" to "升级Pro",
        "pro" to "Pro",
        "subscribe_btn" to "立即订阅 • 每月 $2.99",
        "vip_only" to "仅限VIP",
        "edit_banner" to "编辑封面",

        // POI status / result messages
        "too_far_fmt" to "你必须到达该地点才能操作（距离约 %s 米）。",
        "already_verified" to "你已验证过该地点。",
        "now_verified" to "该地点现已验证！",
        "verification_counted" to "验证已记录。",
        "verify_failed" to "无法记录验证。请检查网络后重试。",
        "already_reported" to "你已举报过该地点。",
        "now_unverified" to "举报过多，该地点已变为未验证。",
        "removed_poi" to "该地点因举报已被移除。",
        "report_counted" to "举报已记录。",
        "report_failed" to "无法记录举报。请检查网络后重试。",

        // Comments
        "comments_title" to "评论",
        "add_comment_hint" to "添加评论...",
        "no_comments" to "还没有评论",
        "word_limit_exceeded" to "超出字数限制！（最多500字）",
        "word_count_fmt" to "%1\$d / 500 字",
        "edit_comment" to "编辑评论",
        "delete" to "删除",
        "report" to "举报",
        "edit" to "编辑",
        "view_full_profile" to "查看完整资料",
        "remove_from_favs" to "从收藏中移除",

        // Map strings
        "found_nearest" to "找到最近的",
        "none_found" to "未找到厕所或垃圾桶。",
        "poi_created" to "地点创建成功！",
        "create_failed" to "创建失败",
        "too_close" to "5米内已存在地点。"
    )

    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> en[key] ?: key
            AppLanguage.CHINESE -> zh[key] ?: en[key] ?: key
        }
    }
}

@Composable
fun string(key: String, themeViewModel: ThemeViewModel): String {
    val lang by themeViewModel.language.collectAsState()
    return AppStrings.get(key, lang)
}
